Peter
ogre0403/ipgod pull request #1
Opened 2016-10-26 08:30 UTC by PeterHKC

2016-10-26 09:33 UTC, ogre0403 requested changes
crawler.py裡的queue module應該是Queue?

2016-10-26 09:38 UTC, ogre0403 requested changes
pydev的設定與pyc檔不需要commit

2016-10-26 16:03 UTC, PeterHKC commented
我這邊用的python是用小寫的
版本是3.5.1的樣子

從我的 iPhone 傳送

> ogre0403 <notifications@github.com> 於 2016年10月26日 下午5:38 寫道：
> 
> @ogre0403 requested changes on this pull request.
> 
> pydev的設定與pyc檔不需要commit
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-10-28 01:16 UTC, ogre0403 commented
我改成3.5.1後可執行。
metadata裡的getLogFile()裡建的目錄結構和檔案內容為何?幫我寫個註解。
pydev的設定與pyc檔拿掉後後再送一次pull request. 
我就把這個pr關掉

2016-10-28 05:50 UTC, PeterHKC commented
收到。
抱歉記錯版本，應該是3.5.2
[image: 內置圖片 1]

2016-10-28 9:16 GMT+08:00 ogre0403 <notifications@github.com>:

> 我改成3.5.1後可執行。
> metadata裡的getLogFile()裡建的目錄結構和檔案內容為何?幫我寫個註解。
> pydev的設定與pyc檔拿掉後後再送一次pull request.
> 我就把這個pr關掉
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ogre0403/ipgod/pull/1#issuecomment-256812845>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AVj9aq_TeQBU5_jYLq3A8JPBg3z5oaSYks5q4Uz_gaJpZM4Kg5Ig>
> .
>

2016-11-04 03:17 UTC, ogre0403 commented
Fetcher.py的line 45與metadata.py的line128的print改用logger.debug輸出

2016-11-04 03:18 UTC, ogre0403 commented
除了downloadURL後，還有可能會出現accessURL, 要再考慮從accessURL下載的功能

2016-11-04 11:01 UTC, PeterHKC commented
收到

從我的 iPhone 傳送

> ogre0403 <notifications@github.com> 於 2016年11月4日 上午11:18 寫道：
> 
> 除了downloadURL後，還有可能會出現accessURL, 要再考慮從accessURL下載的功能
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-11-16 02:43 UTC, merged